
quarkus:
  http:
    port: 8080
  datasource:
    db-kind: postgresql
    username: postgres
    password: 12345
    jdbc:
      url: jdbc:postgresql://localhost/postgres
  hibernate-orm:
    database:
      generation:
        ~: none




"%test":
   quarkus:
     datasource:
       db-kind: h2
       jdbc:
         url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_DELAY=-1
     hibernate-orm:
       sql-load-script: sql/import-test.sql
       database:
         generation:
           ~: drop-and-create
           create-schemas: true